"""Build the canonical, deterministic report data structure.

Every renderer (JSON, Markdown, HTML) consumes the dictionary produced here, so
the three outputs always agree. The structure contains no wall-clock time: the
only timestamp is the SBOM's own metadata timestamp, which is part of the input
and therefore deterministic.
"""

from __future__ import annotations

from typing import Any

from .. import APP_NAME, APP_TAGLINE
from ..models import POSTURE_SEVERITY, AnalysisResult, ComponentResult

REPORT_SCHEMA_VERSION = "1.0"

DISCLAIMER = (
    "This report is generated automatically by software. It is NOT legal advice and does "
    "not create a lawyer-client relationship. The classifications are indicative only, depend "
    "entirely on the policy in force at the time of analysis, and may be incomplete or wrong "
    "for your specific facts. Licence interpretation depends on how a component is used "
    "(including linking, modification, and distribution model), which this tool does not "
    "determine. Do not make a distribution decision on the basis of this report alone. Have "
    "the results, and any component marked 'allowed', reviewed by qualified legal counsel "
    "before distributing your product."
)

LIMITATIONS = (
    "This tool analyses the component set described by the SBOM only; it is no better than the "
    "SBOM it is given. It does not detect missing components.",
    "It does not perform linkage analysis (static vs dynamic). This particularly affects "
    "weak-copyleft (e.g. LGPL, MPL) assessment, which is therefore surfaced for review.",
    "It is not a vulnerability scanner. Vulnerability data, if shown, is taken from the SBOM "
    "as-is and is never generated by this tool.",
    "It does not assert CRA compliance or any certification. It is a readiness and analysis "
    "aid only.",
    "Licence resolution covers SPDX identifiers and expressions. Free-text licence names that "
    "are not valid SPDX are treated as unresolved rather than guessed.",
    "Exceptions match a component name with an exact version (or '*'); version ranges are not "
    "supported in this version.",
)


def _methodology() -> list[str]:
    return [
        "Each component's licence information is read from the SBOM. Concluded licence "
        "information is preferred over declared. Where several licence statements are present "
        "without an explicit SPDX expression joining them, they are combined conjunctively "
        "(AND), which is the conservative reading.",
        "Licence identifiers are normalised to SPDX (including resolving deprecated ids), and "
        "SPDX expressions are parsed. The expression is then evaluated against the policy: "
        "'A OR B' allows choosing the most permissive option (the best posture wins, as in "
        "dual licensing); 'A AND B' requires satisfying every licence (the most restrictive "
        "posture wins and obligations accumulate); 'A WITH exception' uses the base licence's "
        "posture unless the policy has an explicit rule for the whole expression.",
        "Anything that cannot be resolved — NOASSERTION, NONE, a non-SPDX or unrecognised "
        "identifier, an unparseable expression, an expression containing any unrecognised "
        "identifier, or no licence at all — is assigned the policy's conservative default "
        "category and is listed separately. Uncertainty never resolves to 'allowed'.",
        "Every classification records the policy rule that produced it, so each result can be "
        "audited. The overall posture is the most restrictive posture among all components.",
        "Project exceptions are applied after classification. An exception overrides the "
        "posture for a named component and version and is recorded, with its justification, "
        "owner, and date, in the exceptions section.",
        "Output is deterministic: components are ordered worst-posture-first and then "
        "alphabetically, and no wall-clock timestamp is included.",
    ]


def _interpretation(result: AnalysisResult) -> str:
    counts = result.counts
    if result.overall_posture == "blocked":
        return (
            f"This component set is NOT ready to ship in a proprietary, commercially "
            f"distributed product as it stands. {counts.blocked} component(s) are blocked under "
            f"the current policy and must be removed, replaced, isolated behind a reviewed "
            f"boundary, or separately licensed. {counts.review} require review."
        )
    if result.overall_posture == "review":
        return (
            f"This component set has no blocked components under the current policy, but it is "
            f"not cleared to ship without review: {counts.review} component(s) require legal "
            f"review (of which {counts.unresolved} could not be resolved automatically)."
        )
    return (
        "Under the current policy, no component is blocked or flagged for review. Standard "
        "attribution and notice obligations still apply and the disclaimer below still holds."
    )


def _component_dict(result: ComponentResult) -> dict[str, Any]:
    component = result.component
    categories: list[str] = []
    for sc in result.symbol_classifications:
        if sc.category not in categories:
            categories.append(sc.category)
    return {
        "name": component.name,
        "version": component.version,
        "purl": component.purl,
        "supplier": component.supplier,
        "author": component.author,
        "license_expression": result.normalized_expression,
        "license_source": result.license_source,
        "categories": categories,
        "posture": result.final_posture,
        "base_posture": result.base_posture,
        "unresolved": result.unresolved,
        "unresolved_reason": result.unresolved_reason,
        "obligations": list(result.obligations),
        "rules_applied": list(result.rule_ids),
        "explanation": result.posture_explanation,
        "symbols": [
            {
                "license_key": sc.license_key,
                "known": sc.known,
                "category": sc.category,
                "posture": sc.posture,
                "rule_id": sc.rule_id,
                "note": sc.note,
            }
            for sc in result.symbol_classifications
        ],
        "exception": (
            {
                "override_posture": result.exception.override_posture,
                "original_posture": result.exception.original_posture,
                "justification": result.exception.justification,
                "owner": result.exception.owner,
                "date": result.exception.date,
            }
            if result.exception is not None
            else None
        ),
    }


def _sort_key(result: ComponentResult) -> tuple[int, str, str]:
    # Worst posture first, then alphabetical by name/version (deterministic).
    return (
        -POSTURE_SEVERITY[result.final_posture],
        result.component.name.casefold(),
        result.component.display_version,
    )


def _aggregate_obligations(results: tuple[ComponentResult, ...]) -> list[dict[str, Any]]:
    by_obligation: dict[str, list[str]] = {}
    for result in results:
        identifier = f"{result.component.name} {result.component.display_version}".strip()
        for obligation in result.obligations:
            by_obligation.setdefault(obligation, [])
            if identifier not in by_obligation[obligation]:
                by_obligation[obligation].append(identifier)
    return [
        {"obligation": obligation, "components": sorted(components)}
        for obligation, components in sorted(by_obligation.items())
    ]


def _vulnerabilities(results: tuple[ComponentResult, ...]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for result in sorted(results, key=_sort_key):
        component = result.component
        if not component.vulnerabilities:
            continue
        out.append(
            {
                "name": component.name,
                "version": component.version,
                "vulnerabilities": [
                    {
                        "id": v.id,
                        "severity": v.severity,
                        "source": v.source,
                        "description": v.description,
                    }
                    for v in component.vulnerabilities
                ],
            }
        )
    return out


def build_report_data(
    result: AnalysisResult, *, include_vulnerabilities: bool = False
) -> dict[str, Any]:
    """Build the canonical report dictionary from an :class:`AnalysisResult`."""
    ordered = sorted(result.results, key=_sort_key)

    data: dict[str, Any] = {
        "report_schema_version": REPORT_SCHEMA_VERSION,
        "tool": {
            "name": result.tool_name or APP_NAME,
            "version": result.tool_version,
            "tagline": APP_TAGLINE,
        },
        "policy": {
            "name": result.policy.name,
            "version": result.policy.version,
            "description": result.policy.description,
            "source": result.policy.source_path,
        },
        "sbom": {
            "format": result.sbom.sbom_format,
            "spec_version": result.sbom.spec_version,
            "document_name": result.sbom.document_name,
            "metadata_timestamp": result.sbom.metadata_timestamp,
            "source_path": result.sbom.source_path,
            "component_count": result.counts.total,
        },
        "summary": {
            "overall_posture": result.overall_posture,
            "interpretation": _interpretation(result),
            "counts": {
                "total": result.counts.total,
                "allowed": result.counts.allowed,
                "review": result.counts.review,
                "blocked": result.counts.blocked,
                "unresolved": result.counts.unresolved,
                "exceptions_applied": result.counts.exceptions_applied,
            },
            "gate": {
                "fail_on": list(result.gate_fail_on),
                "failed": result.gate_failed,
            },
        },
        "risk_register": [_component_dict(r) for r in ordered],
        "unresolved": [
            {
                "name": r.component.name,
                "version": r.component.version,
                "reason": r.unresolved_reason,
                "posture": r.final_posture,
            }
            for r in ordered
            if r.unresolved
        ],
        "obligations": _aggregate_obligations(result.results),
        "exceptions_applied": [
            {
                "component": r.exception.component,
                "version": r.exception.version,
                "override_posture": r.exception.override_posture,
                "original_posture": r.exception.original_posture,
                "justification": r.exception.justification,
                "owner": r.exception.owner,
                "date": r.exception.date,
            }
            for r in ordered
            if r.exception is not None
        ],
        "methodology": _methodology(),
        "limitations": list(LIMITATIONS),
        "disclaimer": DISCLAIMER,
    }

    if include_vulnerabilities:
        data["vulnerabilities"] = _vulnerabilities(result.results)

    return data
