"""Render the report data as Markdown for a legal reader."""

from __future__ import annotations

from typing import Any

_POSTURE_LABEL = {
    "allowed": "Allowed",
    "review": "Review",
    "blocked": "Blocked",
}


def _esc(value: Any) -> str:
    """Escape a value for use inside a Markdown table cell."""
    if value is None:
        return "—"
    text = str(value)
    return text.replace("|", "\\|").replace("\n", " ").strip() or "—"


def _posture(value: str) -> str:
    return _POSTURE_LABEL.get(value, value)


def render_markdown(data: dict[str, Any]) -> str:
    tool = data["tool"]
    policy = data["policy"]
    sbom = data["sbom"]
    summary = data["summary"]
    counts = summary["counts"]
    lines: list[str] = []
    add = lines.append

    add("# Open-source licence risk report")
    add("")
    add(f"Generated by {tool['name']} {tool['version']} — {tool['tagline']}.")
    add("")

    # Disclaimer up front.
    add("> **Disclaimer.** " + data["disclaimer"])
    add("")

    add("## Subject")
    add("")
    add(f"- **SBOM:** {_esc(sbom['document_name'])} "
        f"({sbom['format']} {sbom['spec_version']}, {sbom['component_count']} components)")
    if sbom["source_path"]:
        add(f"- **Source file:** {_esc(sbom['source_path'])}")
    if sbom["metadata_timestamp"]:
        add(f"- **SBOM timestamp:** {_esc(sbom['metadata_timestamp'])}")
    add(f"- **Policy:** {_esc(policy['name'])} (version {_esc(policy['version'])})")
    if policy["source"]:
        add(f"- **Policy source:** {_esc(policy['source'])}")
    add("")

    # Executive summary.
    add("## Executive summary")
    add("")
    add(f"**Overall release posture: {_posture(summary['overall_posture']).upper()}**")
    add("")
    add(summary["interpretation"])
    add("")
    add("| Posture | Components |")
    add("| --- | ---: |")
    add(f"| Blocked | {counts['blocked']} |")
    add(f"| Review | {counts['review']} |")
    add(f"| Allowed | {counts['allowed']} |")
    add(f"| **Total** | **{counts['total']}** |")
    add("")
    add(f"Of these, {counts['unresolved']} could not be resolved automatically, and "
        f"{counts['exceptions_applied']} have a project exception applied.")
    add("")
    gate = summary["gate"]
    if gate["fail_on"]:
        outcome = "FAILED" if gate["failed"] else "passed"
        add(f"Gate (fail on: {', '.join(gate['fail_on'])}): **{outcome}**.")
        add("")

    # Risk register.
    add("## Risk register")
    add("")
    add("| Component | Version | Licence | Category | Posture | Rule applied | Obligations |")
    add("| --- | --- | --- | --- | --- | --- | --- |")
    for c in data["risk_register"]:
        licence = c["license_expression"] or "(unresolved)"
        categories = ", ".join(c["categories"]) if c["categories"] else "—"
        rules = "; ".join(c["rules_applied"]) if c["rules_applied"] else "—"
        obligations = "; ".join(c["obligations"]) if c["obligations"] else "—"
        posture = _posture(c["posture"])
        if c["exception"] is not None:
            posture += f" (exception; was {_posture(c['base_posture'])})"
        add(
            f"| {_esc(c['name'])} | {_esc(c['version'])} | {_esc(licence)} | "
            f"{_esc(categories)} | {_esc(posture)} | {_esc(rules)} | {_esc(obligations)} |"
        )
    add("")

    # Unresolved components.
    add("## Unresolved and unknown components")
    add("")
    if data["unresolved"]:
        add("These components could not be resolved to a known licence and were given the "
            "policy's conservative default. They need human attention before distribution.")
        add("")
        add("| Component | Version | Posture | Reason |")
        add("| --- | --- | --- | --- |")
        for u in data["unresolved"]:
            add(f"| {_esc(u['name'])} | {_esc(u['version'])} | {_esc(_posture(u['posture']))} "
                f"| {_esc(u['reason'])} |")
    else:
        add("None. Every component resolved to a known licence.")
    add("")

    # Obligations.
    add("## Obligations to satisfy before distribution")
    add("")
    if data["obligations"]:
        add("The following obligations arise from the components above. Satisfying them is "
            "necessary but not by itself sufficient; see the disclaimer.")
        add("")
        for item in data["obligations"]:
            components = ", ".join(item["components"])
            add(f"- {item['obligation']}")
            add(f"  - Applies to: {components}")
    else:
        add("No specific obligations were derived. Standard good practice still applies.")
    add("")

    # Exceptions.
    add("## Exceptions applied")
    add("")
    if data["exceptions_applied"]:
        add("| Component | Version | Override | Was | Justification | Owner | Date |")
        add("| --- | --- | --- | --- | --- | --- | --- |")
        for e in data["exceptions_applied"]:
            add(
                f"| {_esc(e['component'])} | {_esc(e['version'])} | "
                f"{_esc(_posture(e['override_posture']))} | {_esc(_posture(e['original_posture']))} "
                f"| {_esc(e['justification'])} | {_esc(e['owner'])} | {_esc(e['date'])} |"
            )
    else:
        add("No exceptions were applied.")
    add("")

    # Optional vulnerabilities section.
    if "vulnerabilities" in data:
        add("## Vulnerabilities reported in the SBOM (informational)")
        add("")
        add("This section reproduces vulnerability data already present in the SBOM. "
            "It is not generated or verified by this tool and is separate from licence "
            "analysis.")
        add("")
        if data["vulnerabilities"]:
            add("| Component | Version | ID | Severity | Source |")
            add("| --- | --- | --- | --- | --- |")
            for v in data["vulnerabilities"]:
                for entry in v["vulnerabilities"]:
                    add(
                        f"| {_esc(v['name'])} | {_esc(v['version'])} | {_esc(entry['id'])} "
                        f"| {_esc(entry['severity'])} | {_esc(entry['source'])} |"
                    )
        else:
            add("No vulnerability data was present in the SBOM.")
        add("")

    # Methodology.
    add("## Methodology")
    add("")
    for paragraph in data["methodology"]:
        add(f"- {paragraph}")
    add("")

    # Limitations.
    add("## Known limitations")
    add("")
    for limitation in data["limitations"]:
        add(f"- {limitation}")
    add("")

    # Full disclaimer (repeated, clearly separated).
    add("## Disclaimer")
    add("")
    add(data["disclaimer"])
    add("")

    return "\n".join(lines)
