"""Assemble the third-party attribution notices file (text and Markdown).

This is the cargo-about-equivalent deliverable. It lists every third-party
component with its attribution details, then reproduces the licence text for each
distinct licence. Licence text is sourced, in order of preference, from:

1. text embedded in the SBOM for the component;
2. the bundled, verbatim SPDX licence-text store; otherwise
3. an explicit pointer to the canonical SPDX page.

The tool never invents or paraphrases licence text.
"""

from __future__ import annotations

import importlib.resources
from functools import cache

from .. import APP_NAME
from ..models import AnalysisResult, ComponentResult

_TEXTS_PACKAGE = "sbom_counsel.data.license_texts"

_NOTICES_HEADER = (
    "This file lists the third-party components included in this product, as recorded "
    "in the software bill of materials, together with their licences and the licence "
    "texts required for attribution. It is generated automatically from the SBOM and is "
    "provided to help satisfy attribution and notice-retention obligations. It is not "
    "legal advice; confirm completeness with qualified counsel before distribution."
)


@cache
def bundled_license_text(license_id: str) -> str | None:
    """Return the bundled verbatim licence text for an SPDX id, if available."""
    resource = importlib.resources.files(_TEXTS_PACKAGE).joinpath(f"{license_id}.txt")
    try:
        if resource.is_file():
            return resource.read_text(encoding="utf-8").rstrip("\n")
    except (FileNotFoundError, OSError):
        return None
    return None


def _attribution_lines(result: ComponentResult) -> list[str]:
    component = result.component
    licence = result.normalized_expression or "unresolved (see risk report)"
    lines = [f"{component.name} {component.display_version}"]
    lines.append(f"    Licence: {licence}")
    if component.supplier:
        lines.append(f"    Supplier: {component.supplier}")
    if component.author and component.author != component.supplier:
        lines.append(f"    Author: {component.author}")
    if component.copyright:
        lines.append(f"    Copyright: {component.copyright}")
    if component.homepage:
        lines.append(f"    Homepage: {component.homepage}")
    return lines


def _distinct_license_ids(results: tuple[ComponentResult, ...]) -> list[str]:
    ids: list[str] = []
    for result in results:
        for sc in result.symbol_classifications:
            if sc.known and sc.license_key not in ids:
                ids.append(sc.license_key)
    return sorted(ids)


def _embedded_texts(
    results: tuple[ComponentResult, ...],
) -> list[tuple[str, str, str]]:
    """Return (component, name/id, text) for SBOM-embedded licence texts."""
    out: list[tuple[str, str, str]] = []
    for result in sorted(results, key=lambda r: r.component.name.casefold()):
        for embedded in result.component.embedded_texts:
            label = embedded.license_id or embedded.name or "licence text"
            out.append(
                (
                    f"{result.component.name} {result.component.display_version}",
                    label,
                    embedded.text.rstrip("\n"),
                )
            )
    return out


def _spdx_pointer(license_id: str) -> str:
    return (
        f"Full licence text is not bundled with this tool. See the canonical text at "
        f"https://spdx.org/licenses/{license_id}.html"
    )


def _sorted_results(result: AnalysisResult) -> tuple[ComponentResult, ...]:
    return tuple(
        sorted(
            result.results,
            key=lambda r: (r.component.name.casefold(), r.component.display_version),
        )
    )


def render_notices_text(result: AnalysisResult) -> str:
    """Render the attribution notices as plain text."""
    results = _sorted_results(result)
    width = 78
    rule = "=" * width
    lines: list[str] = []
    add = lines.append

    add("THIRD-PARTY SOFTWARE NOTICES AND ATTRIBUTIONS")
    if result.sbom.document_name:
        add(f"For: {result.sbom.document_name}")
    add(f"Generated by {APP_NAME} {result.tool_version}")
    add("")
    add(_NOTICES_HEADER)
    add("")
    add(rule)
    add("COMPONENTS")
    add(rule)
    add("")
    if results:
        for r in results:
            lines.extend(_attribution_lines(r))
            add("")
    else:
        add("No components were listed in the SBOM.")
        add("")

    add(rule)
    add("LICENCE TEXTS")
    add(rule)
    add("")
    license_ids = _distinct_license_ids(results)
    if license_ids:
        for license_id in license_ids:
            add(f"---- {license_id} " + "-" * max(0, width - 6 - len(license_id)))
            text = bundled_license_text(license_id)
            add(text if text is not None else _spdx_pointer(license_id))
            add("")
    else:
        add("No recognised SPDX licences were found among the components.")
        add("")

    embedded = _embedded_texts(results)
    if embedded:
        add(rule)
        add("LICENCE TEXTS PROVIDED IN THE SBOM")
        add(rule)
        add("")
        for component, label, text in embedded:
            add(f"---- {component} — {label} " + "-" * 8)
            add(text)
            add("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_notices_markdown(result: AnalysisResult) -> str:
    """Render the attribution notices as Markdown."""
    results = _sorted_results(result)
    lines: list[str] = []
    add = lines.append

    add("# Third-party software notices and attributions")
    add("")
    if result.sbom.document_name:
        add(f"For: **{result.sbom.document_name}**")
        add("")
    add(f"Generated by {APP_NAME} {result.tool_version}.")
    add("")
    add(_NOTICES_HEADER)
    add("")

    add("## Components")
    add("")
    if results:
        for r in results:
            component = r.component
            licence = r.normalized_expression or "unresolved (see risk report)"
            add(f"### {component.name} {component.display_version}")
            add("")
            add(f"- Licence: `{licence}`")
            if component.supplier:
                add(f"- Supplier: {component.supplier}")
            if component.author and component.author != component.supplier:
                add(f"- Author: {component.author}")
            if component.copyright:
                add(f"- Copyright: {component.copyright}")
            if component.homepage:
                add(f"- Homepage: {component.homepage}")
            add("")
    else:
        add("No components were listed in the SBOM.")
        add("")

    add("## Licence texts")
    add("")
    license_ids = _distinct_license_ids(results)
    if license_ids:
        for license_id in license_ids:
            add(f"### {license_id}")
            add("")
            text = bundled_license_text(license_id)
            if text is not None:
                add("```")
                add(text)
                add("```")
            else:
                add(_spdx_pointer(license_id))
            add("")
    else:
        add("No recognised SPDX licences were found among the components.")
        add("")

    embedded = _embedded_texts(results)
    if embedded:
        add("## Licence texts provided in the SBOM")
        add("")
        for comp_name, label, text in embedded:
            add(f"### {comp_name} — {label}")
            add("")
            add("```")
            add(text)
            add("```")
            add("")

    return "\n".join(lines).rstrip("\n") + "\n"
